---
sidebar: sidebar 
permalink: install-setup/cluster-setup.html 
keywords: afx, afx system, cluster setup, setup 
summary: '安装 AFX 硬件后，您可以完成 ONTAP 集群设置。此过程涉及您应按顺序执行的相关配置阶段。作为其中的一部分，您可以选择添加运行 AI Data Engine (AIDE) 的数据计算节点 (DCN)，使 AFX 存储集群和 DCN 集群能够作为通过相同的 ONTAP 控制平面管理的单个系统运行。' 
---
= 设置 AFX 存储系统ONTAP集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安装 AFX 硬件后，您可以完成 ONTAP 集群设置。此过程涉及您应按顺序执行的相关配置阶段。作为其中的一部分，您可以选择添加运行 AI Data Engine (AIDE) 的数据计算节点 (DCN)，使 AFX 存储集群和 DCN 集群能够作为通过相同的 ONTAP 控制平面管理的单个系统运行。



== 准备设置 AFX 存储系统

在设置 ONTAP 集群之前，您应该查看核心 AFX 要求和其他 AIDE 注意事项，以确保您拥有成功完成设置过程所需的所有必要信息和资源。



=== 核心 AFX 要求

设置 AFX 集群时需要考虑几个核心要求。

.硬件安装
确保您已完成 AFX 系统的硬件安装。有关详细信息，请参见link:../install-setup/install-setup-workflow.html["安装您的 AFX 系统"]。

.基本 IP 寻址
您需要以下 IP 地址配置：

* 集群管理 IP 地址
+
集群管理 IP 地址是集群管理员用来访问管理 SVM 和管理集群的集群管理接口的唯一 IPv4 地址。您可以从组织中负责分配 IP 地址的管理员处获取此 IP 地址。

* 网络子网掩码
+
在集群设置期间， ONTAP需要一组适合您的配置的网络接口。如有必要，您可以调整建议。



.其他网络配置
您还需要以下相关网络信息：

* 网络网关 IP 地址
* DNS 域名
* DNS 名称服务器 IP 地址
* NTP 服务器 IP 地址
* 子网掩码




=== 其他 AIDE 注意事项

首次安装和设置 AFX 时，您可以选择包括 NetApp AI Data Engine (AIDE)。AIDE 支持两种部署模式：第三方服务器上的 AIDE 软件或 NetApp 提供的数据计算节点 (DCN)。如果您计划设置 AIDE，请先完成部署模型的先决条件：

* 对于第三方服务器部署，完成 https://docs.netapp.com/us-en/ai-data-engine/install-aide-server/aide-mde-server-hardware-requirements.html["第三方服务器上 AI Data Engine 的硬件安装"^]，然后 https://docs.netapp.com/us-en/ai-data-engine/install-setup/install-aide-as-software.html["在第三方服务器上安装 AIDE 软件"^]。
* 对于 NetApp DCN 部署，请完成 https://docs.netapp.com/us-en/ai-data-engine/install-dcn/aide-dcn-hardware-requirements.html["在 NetApp 提供的数据计算节点上安装 AI Data Engine 的硬件"^]。
* 获取计算节点的地址和任何相关网络配置。




== 执行初始集群设置

您可以将笔记本电脑设备连接到 AFX 集群并设置几个全局配置值。

.关于此任务
AFX 集群有四个区域必须进行初始配置。前三个是必需的，最后一个是可选的。

.步骤
. 发现您的集群网络。
+
.. 将您的笔记本电脑连接到管理交换机并访问网络计算机和设备。
.. 打开文件资源管理器。
.. 选择*网络*；然后右键单击并选择*刷新*。
.. 选择任一ONTAP图标；然后接受屏幕上显示的任何证书。
+
将显示系统管理器用户界面。



. 设置管理员密码。
+
提供并验证 `admin`帐户。选择*继续*。

. 配置 AFX 集群和控制器节点的 IP 地址。
+
提供 IP 地址和子网掩码。

. 如果要在 AFX 存储系统上安装 AI Data Engine，请提供三个计算节点的 IP 地址。
. 配置网络服务，包括 DNS 和 NIS。选择 *Continue*。
+
定义您的 DNS 和 NTP 服务器的详细信息。

. 可选择设置加密。
+
您可以定义集群加密的详细信息。选择*继续*。

+

NOTE: 有关如何在非 Windows 环境中创建集群的信息，请参阅 link:https://docs.netapp.com/us-en/ontap/software_setup/setup-cluster.html["创建ONTAP集群并加入节点"^]。



.下一步
您将被重定向到系统管理员登录页面。执行中描述的步骤<<完成集群设置>>。



== 完成集群设置

完成初始配置后，您可以使用系统管理器完成ONTAP集群设置。

.关于此任务
在设置过程中配置了 AFX 系统ONTAP集群的三个区域。如果可能的话，请完成所有三个，但只需要第一个。

.开始之前
您需要掌握以下信息：

* VLAN 配置详细信息。
* NAS 和/或 S3 配置详细信息。


.步骤
. 使用您在初始集群设置期间提供的管理员帐户Sign in系统管理器。请注意右上角的弹出窗口，其中有三个配置选项。
. 选择*VLAN 和标记*并选择适合您环境的网络选项。
. 选择*网络服务*并配置默认数据 SVM 的客户端访问协议。
. 选择*数据容器*并创建卷或 S3 存储桶。


.下一步
* 如果您将 AIDE 作为 AFX 集群设置的一部分，请完成其他 AIDE 配置步骤。身份验证配置适用于所有 AIDE 部署。使用许可 AIDE 功能的 NetApp DCN 部署需要许可证；第三方服务器部署以元数据为重点，不需要 AIDE 许可证。有关详细信息，请参见 https://docs.netapp.com/us-en/ai-data-engine/install-setup/cluster-setup-afx.html["设置 AI Data Engine"^]。
* 你应该link:../get-started/prepare-cluster-admin.html["准备管理 AFX"]在生产环境中使用 AFX 集群之前。




== 相关信息

* link:../get-started/learn-about-aide.html["了解 NetApp AI Data Engine"]
* link:../administer/configure-svm.html["配置 AFX SVM"]
* link:../get-started/prepare-cluster-admin.html["准备管理 AFX"]

