---
sidebar: sidebar 
permalink: install-setup/cluster-setup.html 
keywords: afx, afx system, cluster setup, setup 
summary: 安装 AFX 硬件后，您可以完成集群设置。此过程涉及两个相关的配置阶段，您需要按顺序执行。 
---
= 设置 AFX 存储系统ONTAP集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安装 AFX 硬件后，您可以完成ONTAP集群设置。此过程涉及两个相关的配置阶段，您需要按顺序执行。



== 执行初始集群设置

您可以将笔记本电脑设备连接到 AFX 集群并设置几个全局配置值。

.关于此任务
AFX 集群有四个区域必须进行初始配置。前三个是必需的，最后一个是可选的。

.开始之前
您需要掌握以下信息：

* 集群管理 IP 地址
+
集群管理 IP 地址是集群管理员用来访问管理 SVM 和管理集群的集群管理接口的唯一 IPv4 地址。您可以从组织中负责分配 IP 地址的管理员处获取此 IP 地址。

* 网络子网掩码
+
在集群设置期间， ONTAP需要一组适合您的配置的网络接口。如有必要，您可以调整建议。



您还需要以下物品：

* 网络网关 IP 地址
* DNS 域名
* DNS 名称服务器 IP 地址
* NTP 服务器 IP 地址
* 数据子网掩码


.步骤
. 发现您的集群网络。
+
.. 将您的笔记本电脑连接到管理交换机并访问网络计算机和设备。
.. 打开文件资源管理器。
.. 选择*网络*；然后右键单击并选择*刷新*。
.. 选择任一ONTAP图标；然后接受屏幕上显示的任何证书。
+
将显示系统管理器用户界面。



. 设置管理员密码。
+
提供并验证 `admin`帐户。选择*继续*。

. 配置集群和控制节点的IP地址。
+
提供 IP 地址和子网掩码。

. 配置网络服务。选择*继续*。
+
定义您的 DNS 和 NTP 服务器的详细信息。

. 可选择设置加密。
+
您可以定义集群加密的详细信息。选择*继续*。



.下一步
您将被重定向到系统管理员登录页面。执行中描述的步骤<<完成集群设置>>。



== 完成集群设置

完成初始配置后，您可以使用系统管理器完成ONTAP集群设置。

.关于此任务
在设置过程中配置了 AFX 系统ONTAP集群的三个区域。如果可能的话，请完成所有三个，但只需要第一个。

.开始之前
您需要掌握以下信息：

* VLAN 配置详细信息。
* NAS 和/或 S3 配置详细信息。


.步骤
. 使用您在初始集群设置期间提供的管理员帐户Sign in系统管理器。请注意右上角的弹出窗口，其中有三个配置选项。
. 选择*VLAN 和标记*并选择适合您环境的网络选项。
. 选择*网络服务*并配置默认数据 SVM 的客户端访问协议。
. 选择*数据容器*并创建卷或 S3 存储桶。


.下一步
你应该link:../get-started/prepare-cluster-admin.html["准备管理 AFX"]在生产环境中使用 AFX 集群之前。

.相关信息
* link:../administer/configure-svm.html["配置 AFX 数据 SVM"]
* link:../get-started/prepare-cluster-admin.html["准备管理 AFX"]

