---
sidebar: sidebar 
permalink: secure-data/prepare-secure-data.html 
keywords: afx, afx system, prepare, prepare secure, prepare secure data 
summary: 在管理 AFX 数据之前，您应该熟悉主要概念和功能。 
---
= 准备保护您的 AFX 存储系统数据
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在管理 AFX 数据之前，您应该熟悉主要概念和功能。



== 术语和选项

您应该熟悉几个与 AFX 数据安全相关的术语。

勒索软件:: 勒索软件是一种恶意软件，它会加密文件，使用户无法访问它们。通常情况下，解密数据需要支付一定的费用。  ONTAP通过自主勒索软件防护 (ARP) 等功能提供抵御勒索软件的解决方案。
加密:: 加密是将数据转换为安全格式的过程，未经适当授权就无法轻易读取。ONTAP提供基于软件和基于硬件的加密技术来保护静态数据。这确保了当存储介质被重新利用、退回、放错地方或被盗时，它无法被读取。这些加密解决方案可以使用外部密钥管理服务器或ONTAP提供的板载密钥管理器进行管理。请参阅link:../secure-data/encrypt-data-at-rest.html["加密 AFX 存储系统上的静态数据"]了解更多信息。
数字证书和 PKI:: 数字证书是用于证明公钥所有权的电子文档。公钥和相关的私钥可以以多种方式使用，包括通常作为更大的安全框架（如 TLS 和 IPsec）的一部分来建立身份。这些密钥以及支持协议和格式标准构成了公钥基础设施 (PKI) 的基础。请参阅link:../administer/manage-certificates.html#generate-a-certificate-signing-request["管理 AFX 存储系统上的证书"]了解更多信息。
互联网协议安全:: IPsec 是一种互联网标准，它为网络端点之间在 IP 层传输的数据提供传输中的数据加密、完整性和身份验证。它能保护ONTAP与客户端之间的所有 IP 流量，包括 NFS 和 SMB 等更高级别的协议。 IPsec 可保护您的数据免受恶意重放攻击和中间人攻击。请参阅link:../secure-data/secure-ip-connections.html["AFX 存储系统上的安全 IP 连接"]了解更多信息。




== 相关信息

* link:../administer/additional-ontap-svm.html["额外的 AFX SVM 管理"]
* link:../get-started/prepare-cluster-admin.html["准备管理您的 AFX 系统"]

