---
sidebar: sidebar 
permalink: get-started/compare-unified-ontap.html 
keywords: afx, afx system, compare afx, compare unified ontap 
summary: NetApp AFX 系统运行定制的ONTAP特性，它与在AFF和FAS存储上运行的ONTAP特性（称为统一ONTAP ）不同。您应该了解 AFX 系统与FAS和AFF系统有何相似之处和不同之处。这提供了宝贵的视角，并且在您的环境中部署 AFX 时会很有帮助。 
---
= 将 AFX 存储系统与AFF和FAS系统进行比较
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp AFX 系统运行定制的ONTAP特性，它与在AFF和FAS存储上运行的ONTAP特性（称为统一ONTAP ）不同。您应该了解 AFX 系统与FAS和AFF系统有何相似之处和不同之处。这提供了宝贵的视角，并且在您的环境中部署 AFX 时会很有帮助。


TIP: AFX 文档包含统一ONTAP文档站点上各种主题的链接，其中详细介绍了无论ONTAP特性如何都以相同方式运行的功能。附加内容提供了更深入的帮助，可以帮助您管理 AFX 存储系统。



== 配置差异

AFX 配置与AFF和FAS系统在一些方面有所不同。

高级容量平衡:: 先进的容量平衡功能，使用 `-gdd`CLI 参数，默认情况下对所有FlexGroup卷启用。




== 不受支持或受限制的 Unified ONTAP功能

NetApp AFX 针对高性能 NAS 和对象工作负载进行了优化。因此，AFF 和 FAS 存储系统存在差异。以下功能不适用于 NetApp AFX；列表按主要功能或功能区域进行组织。您还应根据 ONTAP 版本查看 link:../release-notes/whats-new-9171.html["什么是新的"] 中的 AFX 更新和更改。



=== 块存储和SAN

* SAN 管理和客户端访问
* LUN 和 NVMe 命名空间
* 卷的厚配置




=== 骨料和物理存储

* MetroCluster
* 物理节点拥有的聚合
* RAID 管理
* NetApp聚合加密 (NAE)
* 聚合级重复数据删除
* SyncMirror （聚合镜像）
* FabricPool分层
* 负载共享镜像




=== 数据复制（SnapMirror）


NOTE: Unified ONTAP和 AFX 之间双向支持所有数据复制，并遵循相同的版本控制限制（详见下文）。 https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html["SnapMirror关系兼容的ONTAP版本"^] （除少数例外情况外）。

* 无法从包含 LUN 或 NVMe 命名空间的AFF或FAS系统复制卷
* FlexGroup卷只能从 AFX 复制到 Unified ONTAP版本 9.16.1 或更高版本（因为需要高级容量平衡）。




=== 易管理性

* ONTAPI API（ZAPI）
* 不支持的功能（例如MetroCluster）的 REST API
* REST API 在性能统计方面存在一些初步限制
* AIQ 统一管理器支持
* Grafana Harvest 版本 25.08.1 及更高版本
* NetApp Trident版本 25.10 及更高版本




== 命令行界面的更改

AFX 提供的ONTAP CLI 通常与AFF和FAS系统提供的 CLI 相同。但存在一些差异，包括：

* 与以下相关的新 AFX 命令：
+
** 显示存储可用区域的容量
** 启动媒体


* 没有与 SAN 相关的命令
* 不再需要聚合管理命令
* 聚合显示现在显示整个存储可用区 (SAZ)




== 相关信息

* link:../get-started/system-design.html["AFX系统特性"]
* link:../get-started/software-architecture.html["AFX 架构细节"]
* link:../faq-ontap-afx.html["AFX 存储系统常见问题解答"]
* link:../administer/additional-ontap-cluster.html["额外的 AFX 集群管理"]
* link:../administer/additional-ontap-svm.html["额外的 AFX SVM 管理"]

