---
sidebar: sidebar 
permalink: get-started/ontap-afx-storage.html 
keywords: afx, afx system, learn, workloads, hardware, afx 1k, nx224, cisco 
summary: NetApp AFX 存储系统基于下一代存储架构，将ONTAP存储模型发展为分解的高性能 NAS 解决方案。  AFX 采用先进的技术和处理技巧来支持文件和对象工作负载，从而提供极高的性能。 
---
= 了解 AFX 存储系统
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp AFX 存储系统基于下一代存储架构，将ONTAP存储模型发展为分解的高性能 NAS 解决方案。  AFX 采用先进的技术和处理技巧来支持文件和对象工作负载，从而提供极高的性能。



== 典型的应用程序工作负载

NetApp AFX 存储系统满足 AI/ML 环境和其他相关以数据为中心的应用程序的典型独特需求。AFX 存储系统非常适合管理多种不同工作负载的组织，包括：

* 与深度学习相关的训练和迭代模型细化，需要持续的高带宽和对海量数据集的访问。
* 处理包括文本、图像和视频在内的多种数据类型。
* 需要严格响应时间窗口的低延迟实时推理应用程序。
* 数据科学和机器学习流程可以从数据工程师和数据科学家的自助数据管理中受益。
* 需要高并发性和并行 I/O 的工作负载，例如具有 RDMA 传输的多 GPU 系统。




== 系统设计特点

AFX 系统具有多种设计特点，使其能够作为高性能 NAS 平台运行。

分离存储和计算能力:: 与AFF和FAS存储系统不同，集群的 AFX 存储和计算元素是分离的。  AFX 控制器并不局限于访问有限的一组本地磁盘。
删除聚合和 RAID 管理:: 存储管理员不再需要管理聚合和 RAID 组。  AFX 处理这些任务，从而简化管理并为非专业人员提供管理其数据的机会。
集群的单个存储池:: 将 AFX 计算和存储分离，并简化存储管理，从而形成单一存储池。此存储可用区 (SAZ) 可供 AFX 集群中的所有控制器节点使用。看link:../faq-ontap-afx.html["AFX 存储系统常见问题解答"]了解更多详情。
高性能:: AFX 专为满足专业 AI/ML 应用程序所需的高性能而构建。它可以更有效地利用现代硬件来提供具有超低延迟的高且持续的带宽。
操作简便:: 单一存储池以及包括自动存储管理在内的其他功能提供了更为简单的管理和操作模型。
可扩展性:: 集群中的控制节点和存储架组可以根据应用需求独立扩展。添加控制器或机架时，管理要求和中断有限。
提高数据移动性:: 卷可以在集群控制器节点之间无中断地移动，而无需实际复制数据。而是更新元数据目录和索引指针。这极大地提高了典型管理程序以及故障情况下的恢复性能。




== 硬件基础设施

NetApp AFX 存储系统提供统一的硬件和软件解决方案，可根据高性能 NAS 客户的需求创建简化的体验。

以下硬件组件与 AFX 集群一起使用：

* AFX 1K 控制器
* NX224货架
* Cisco Nexus 9332D-GX2B 或 Nexus 9364D-GX2A 交换机




== 相关信息

* https://www.netapp.com/afx/["NetApp AFX"^]

