---
sidebar: sidebar 
permalink: get-started/ontap-afx-storage.html 
keywords: afx, afx system, learn, workloads, hardware, afx 1k, nx224, cisco 
summary: NetApp AFX 存储系统基于下一代存储架构，将ONTAP存储模型发展为分解的高性能 NAS 解决方案。  AFX 采用先进的技术和处理技巧来支持文件和对象工作负载，从而提供极高的性能。 
---
= 了解 AFX 存储系统
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp AFX 存储系统基于下一代存储架构，将ONTAP存储模型发展为分解的高性能 NAS 解决方案。  AFX 采用先进的技术和处理技巧来支持文件和对象工作负载，从而提供极高的性能。



== 典型的应用程序工作负载

NetApp AFX 存储系统满足了 NAS 和 S3 对象工作负载对高性能和独立扩展的独特需求。这些应用程序受益于基于高并发性和并行 I/O 的先进设计。  AFX 非常适合部署和管理多种不同类型应用程序工作负载的组织，包括：

* 与深度学习相关的训练和迭代模型细化，需要持续的高带宽和对海量数据集的访问。
* 处理包括文本、图像和视频在内的多种数据类型。
* 需要严格响应时间窗口的低延迟实时推理应用程序。
* 数据科学和机器学习流程可以从数据工程师和数据科学家的自助数据管理中受益。




== 系统设计特点

AFX 系统具有多种设计特点，使其能够作为高性能 NAS 平台运行。

分离存储和计算能力:: 与其他NetApp ONTAP存储系统不同，AFX 集群的计算和存储元素是解耦的，并通过交换网络连接。磁盘所有权不再与特定节点绑定，这带来了诸多好处。例如，AFX 集群的计算和存储组件可以独立扩展。
自动化存储管理:: AFX 存储管理员已无法访问物理聚合数据。相反，当向集群添加新的存储架时，AFX 会自动管理节点的虚拟容量分配以及 RAID 组配置。这种设计简化了管理，并为非专业人员提供了管理数据的机会。
集群的单个存储池:: 由于NetApp AFX 将存储节点和机架解耦，因此集群的所有存储容量都集中在一个名为存储可用区 (SAZ) 的池中。 SAZ 中的磁盘和存储架可供 AFX 集群中的所有存储节点进行读写操作。此外，发生故障时，所有集群节点都可以参与磁盘重建。请参阅link:../faq-ontap-afx.html["AFX 存储系统常见问题解答"]更多详情请见下文。
高性能:: NetApp AFX 提供高且持续的带宽以及超低的延迟，因此专为高性能 NAS 和对象工作负载而设计。 AFX 采用最新的现代硬件以及存储机架，凭借其独特的架构，能够处理高比例的节点和磁盘。将存储节点扩展到超过典型的 1:1（节点：机架）比例，可以最大限度地发挥磁盘的性能，使其达到极限。该设计为您的关键应用提供效率和存储密度。
独立且大规模:: 基于解耦的存储节点和存储架，AFX 集群可以根据您的应用需求进行独立且无中断的扩展。您可以添加存储节点来获得更多 CPU 和吞吐量，或者添加存储架来获得更多存储容量和磁盘性能。 NetApp AFX 架构为集群的最大规模带来了新的可能性。有关基于您的ONTAP版本的 AFX 集群的最新限制，请参阅NetAppHardware Universe。
零拷贝数据迁移:: NAS 和对象客户端访问ONTAP集群上的卷。您可以无中断地在节点之间迁移卷，以实现容量和性能平衡目标。使用 Unified ONTAP时，卷迁移是使用SnapMirror技术执行的，这可能需要一些时间并占用额外的临时容量。但是，使用 AFX，在共享存储可用区 (SAZ) 内不再需要数据复制操作。相反，仅移动卷元数据，从而显著提高性能。请参阅link:../faq-ontap-afx.html["AFX 存储系统常见问题解答"]更多详情请见下文。
增强型高可用性功能:: NetApp AFX 为高可用性 (HA) 配置和处理提供了许多增强功能。 AFX 消除了直接连接 HA 伙伴节点的需要，而是允许 HA 对通过内部集群网络进行通信。这种设计使管理员可以选择在数据中心的不同机架或行中部署 HA 对，以增加容错能力。此外，AFX 零拷贝迁移功能还扩展到了高可用性故障转移场景。当一个节点发生故障时，其卷将故障转移到高可用性伙伴节点，以将剩余的写入操作提交到磁盘。然后ONTAP将卷均匀地分配到集群中所有幸存的节点上。这意味着在数据放置的初始设计中，您不再需要考虑存储故障转移性能。




== 硬件基础设施

NetApp AFX 存储系统提供统一的硬件和软件解决方案，可根据高性能 NAS 客户的需求创建简化的体验。


TIP: 你应该复习一下link:../faq-ontap-afx.html["AFX 存储系统常见问题解答"]有关硬件互操作性和升级选项的更多信息。

以下硬件组件与 AFX 集群一起使用：

* AFX 1K 控制器
* NX224货架
* Cisco Nexus 9332D-GX2B 或 Nexus 9364D-GX2A 交换机




== 相关信息

* https://hwu.netapp.com/["NetApp Hardware Universe"^]
* https://www.netapp.com/afx/["NetApp AFX"^]

