---
sidebar: sidebar 
permalink: release-notes/whats-new-9191.html 
keywords: 'afx, release notes, what"s new, 9.19.1' 
summary: 了解您的 AFX 存储系统提供的 ONTAP 9.19.1 附带的新功能。 
---
= AFX 存储系统的 ONTAP 9.19.1 新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
了解您的 AFX 存储系统提供的 ONTAP 9.19.1 附带的新功能。


NOTE: ONTAP 9.19.1 为 AFX 提供了几项新功能。其中一些是针对 AFX 的，而其他许多则来自共同的共享产品基础。除了查看下面描述的 AFX 功能外，您还应参考 https://docs.netapp.com/us-en/ontap/release-notes/whats-new-9191.html["ONTAP 9.19.1 中的新增功能"^]。



[[data-protection]]
== 数据保护

[cols="2,4"]
|===
| 更新 | 描述 


| link:../administer/additional-ontap-svm.html["使用适用于 NAS 的 ONTAP SnapMirror 活动同步进行保护"]  a| 
SnapMirror 活动同步支持在 AFX 集群（仅限 4 节点）上使用 NFS 和 SMB 在 SVM 级别的 NAS 工作负载，并且仅在主集群上支持读写访问。



| link:../manage-data/create-configure-bucket.html["SnapMirror 云支持限制已增加到 100 个 S3 存储桶"]  a| 
SnapMirror cloud 将支持的 S3 存储桶数量增加到 100 个。

|===


[[networking]]
== 网络连接

[cols="2,4"]
|===
| 更新 | 描述 


| link:../administer/additional-ontap-cluster.html#performance["TCP性能改进"]  a| 
从 ONTAP 9.19.1 开始，ONTAP 通过将两个丢包恢复功能 PRR 和 RACK 集成到 ONTAP TCP 堆栈中，提高了有损耗、高延迟 WAN 链路上的 TCP 数据传输性能。

|===


[[performance]]
== 性能

[cols="2,4"]
|===
| 更新 | 描述 


| 跨文件顺序读取 (CFSR)  a| 
Cross File Sequential Read 可以显著提高某些媒体和娱乐工作负载的读取性能。该功能智能地预取顺序视频帧，以显著提高视频编辑应用程序的吞吐量并减少延迟。请查看 link:../administer/additional-ontap-svm.html["AFX 存储系统 SVM 的附加管理"] 以了解更多信息。



| 全局重复数据删除  a| 
全局重复数据删除将 ONTAP 重复数据删除节省的空间扩展到整个存储可用区 (SAZ)。通过消除 SAZ 中所有卷上的重复数据块，它可以显著提高存储效率并降低总拥有成本。该功能在 AFX 系统上默认启用，无需管理配置即可透明运行。有关详细信息，请参见 link:../administer/additional-ontap-svm.html["AFX 存储系统 SVM 的附加管理"]。



| 动态存储效率  a| 
Dynamic Storage Efficiency 智能地针对需要高性能和最大吞吐量的大型工作负载优化存储效率操作（压缩、重复数据删除和压缩）。它自动检测高容量写入条件，并暂时挂起内联和后台存储效率流程，以防止峰值负载期间的性能下降。当吞吐量低于定义的阈值时，存储效率操作将恢复，并且无需手动干预即可恢复节省的成本。该功能在 AFX 存储系统上可用，默认情况下启用，无需配置。

|===


[[rest-api]]
== REST API

[cols="2,4"]
|===
| 更新 | 描述 


| Kubernetes 存储编排的平衡布局增强  a| 
ONTAP 9.19.1 将  `/storage/volumes` REST API 端点中当前可用的六个参数添加到  `/applications/containers` 端点。这种增强功能使使用 NetApp Trident 进行 Kubernetes 存储编排的客户能够使用 ONTAP 的原生平衡放置功能创建卷。

|===


[[s3-object-storage]]
== S3 对象存储

[cols="30%,70%"]
|===
| 更新 | 描述 


 a| 
xref:../manage-data/manage-buckets.html[管理 AFX 存储系统存储桶]
 a| 
您可以使用条件来强制对象上传的条件写入和对象删除的条件删除。条件写入和删除提供了一种防止覆盖或意外删除对象的方法。



 a| 
xref:../manage-data/manage-buckets.html[管理 AFX 存储系统存储桶]
 a| 
为了在原始访问密钥过期时保持用户对 S3 资源的访问，ONTAP 集群管理员可以为每个 S3 用户生成第二个访问密钥。

|===


[[security]]
== 安全性

[cols="2,4"]
|===
| 更新 | 描述 


| https://docs.netapp.com/us-en/ontap/anti-ransomware/use-cases-restrictions-concept.html#snapmirroreligible["对 SnapMirror 主卷的 ARP/AI 支持"^]  a| 
ARP/AI 支持与 AFX 系统的 SnapMirror 同步关系中的合格主卷。ARP/AI 在活动读写主卷上运行，创建仅主 ARP 快照，并提供基于机器学习的勒索软件检测。



| link:../administer/additional-ontap-cluster.html["支持 TLS 硬件卸载"]  a| 
您可以将整个集群的传输层安全性 (TLS) 加密和解密卸载到支持的以太网卡。这减少了 CPU 开销，并提高了使用 TLS 的系统的性能。



| link:../administer/additional-ontap-svm.html["基于 TLS 的 NFS v3"]  a| 
从 ONTAP 9.19.1 开始，ONTAP 添加了对具有 TLS 1.3 的 NFS over TLS 的本地支持，以加密启用 NFS 的 SVM 上传输中的 NFS 流量。该版本还支持可选的每 LIF 双向 TLS 主机身份验证和导出策略控制，以拒绝匹配客户端的非 TLS TCP 访问。

|===


[[storage-resource-management]]
== 存储资源管理

[cols="2,4"]
|===
| 更新 | 描述 


| link:../administer/monitor-cluster-performance.html["System Manager 对存储可用性区域容量详细信息的支持。"]  a| 
您可以在 System Manager 中查看存储可用性区域容量详细信息，包括空间阈值、快照消耗的空间和数据精简。您还可以将空间使用阈值设置为希望 ONTAP 生成警告和严重警报时的百分比。



| link:../administer/additional-ontap-cluster.html["支持修改控制自动 QoS 吞吐量上限增加的默认设置"]  a| 
您可以修改默认设置，以控制 QoS 策略组如何自动增加 QoS 吞吐量上限，以响应对更高性能的短期需求。这些设置在 ONTAP 9.18.1 及更早版本中无法修改。

|===


[[upgrade]]
== 升级

[cols="2,4"]
|===
| 更新 | 描述 


| link:../administer/upgrade-ontap.html["增强的自动升级前检查报告功能"]  a| 
执行自动升级前检查时，将分别显示错误和警告，以帮助您轻松识别升级前必须解决的问题。

|===


[[related-information]]
== 相关信息

* https://docs.netapp.com/us-en/ontap/release-notes/index.html["ONTAP 9 发布亮点"^]

